model:
  target: models.diffusion.Diffusion_TS
  params:
    seq_length: 23
    n_feat: 5
    n_embd: 512
    timesteps: 50
    loss_type: 'l2'
    beta_sch : "cosine"
    n_heads: 4
    mlp_hidden_times: 2
    n_layer_enc : 2
    n_layer_dec : 2
    use_ff : True

solver:
  base_lr: 1.0e-5
  train_epochs: 20000
  results_folder: ./check_points/exp1_stock_st
  save_period : 5000

  scheduler:
    target: utils.lr_scheduler.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 500
      min_lr: 1.0e-9
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 1.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: data.datasets.Stock_Stationary
    params:
      symbol : 'AAPL, MSFT, NVDA, AMZN, COST'
      sdate : '20000101'
      edate : '20231231'
      window: 24 
      train_test : 'train'
      train_ratio : 0.6
      save_ground_truth : True
    shuffle: True

  test_dataset:
    target: data.datasets.Stock_Stationary
    params:
      symbol : 'AAPL, MSFT, NVDA, AMZN, COST'
      sdate : '20000101'
      edate : '20231231'
      window: 24 
      train_test : 'test'
      train_ratio : 0.6
      save_ground_truth : True
    shuffle: False

  batch_size: 128
  